# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'RSS 2027, July 6, 2027 - July 11, 2027, Athens, Greece'
url:              "https://roboticsconference.org"
baseurl:          ""
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']
logo:             "/images/rss2027-banner-preview.png"
favpng:           "/public/RSS2026-favicon.png"
favicon:          "/public/RSS2026-favicon.ico"
apple_touch_icon: "/public/apple-touch-icon-144-precomposed.png"
startdate:        "2027-07-06"
enddate:          "2027-07-11"
location:         "Athens, Greece"


author:
  name:           'Zehao Wang'
  url:            https://zehaowang983.github.io/

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

google_analytics: G-RCJTV6PJZC

collections:
    attending:
       output: false
       permalink: /attending/:path/
       priority: 2
    program:
       output: false
       permalink: /program/:path/
       priority: 2
    committees:
       output: false
       permalink: /committees/:path/
       priority: 4
    information:
       output: true
       permalink: /information/:path/
       priority: 3

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
