# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'RSS 2026, July 13, 2026 - July 17, 2026, Sydney, Australia'
url:              "https://roboticsconference.org"
baseurl:          ""
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']
logo:             "/images/RSS2026-logo.jpg"
favpng:           "/public/RSS2025-favicon-516x516.png"
favicon:          "/public/RSS2025-favicon-256x256.ico"
apple_touch_icon: "/public/apple-touch-icon-144-precomposed.png"
startdate:        "2026-07-13"
enddate:          "2026-07-17"
location:         "Sydney, Australia"


author:
  name:           'Zehao Wang'
  url:            https://zehaowang983.github.io/

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

google_analytics: G-RCJTV6PJZC

collections:
    attending:
       output: true
       permalink: /attending/:path/
       priority: 2
    program:
       output: true
       permalink: /program/:path/
       priority: 2
    committees:
       output: true
       permalink: /committees/:path/
       priority: 4
    information:
       output: true
       permalink: /information/:path/
       priority: 3

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
